### ISSUE TITLE
VS 2022 upgrade would be fantastic

### ISSUE THREAD

**Issue by GlassBeaver** [einaregilsson/ClipboardDiff#2]
Love the plugin, would be awesome for it to work on VS 2022!

**Comment by einaregilsson** [comment]
Do you know if there are any big differences for extensions since the last VS? I don't really use VS anymore, but I can update it if there's not a lot of work involved.

**Comment by GlassBeaver** [comment]
no clue unfortunately - VS extensions are one thing that I've never remotely touched

**Comment by einaregilsson** [comment]
Ok, I'll try to check it out sometime soon and see if upgrading is a hassle.

**Comment by garrofederico** [comment]
Here is a replacement extension:
https://marketplace.visualstudio.com/items?itemName=ryu1kn.partial-diff
